### ISSUE TITLE
File Path Updates Needed in Detector & Evaluator Module

### ISSUE THREAD

**Issue by sagipend** [MarkChenYutian/T5-Sentinel-public#1]
Hi,

When running:
`python3 -m evaluator.calc.calc_accuracy
`
I encounter the following error:

FileNotFoundError: [Errno 2] No such file or directory: 'detector/models/t5_hidden/settings.yaml'
Moreover, when executing:

`from evaluator.interpret.integrated_gradient import explain
`
I encounter a similar issue:
FileNotFoundError: [Errno 2] No such file or directory: 'detector/models/t5_hidden/settings.yaml'

I attempted to correct the paths, but it appears some files are missing, such as the "models-small" directory that needs to be loaded in evaluator.interpret.integrated_gradient.explain. It appears that the repository requires updates regarding file paths and names.

Thank you!

**Comment by haok1402** [comment]
Hi Sagi, thanks for pointing out this issue :) We're actively working on this to put a fix.

1. During training we have used the prefix `detector/models` which we later discovered cumbersome and changed to `detector/` instead. It appears that we haven't fully cleanup the codebase yet that parts of the code are still in the training version. 
2. @MarkChenYutian Could you take a look how `Tokenizer` is initialized under `evaluator/`? I can't remember exactly which model `models-small` is referring to.

**Comment by MarkChenYutian** [comment]
Hi, @sagipend 

Thanks for the issue, we have updated the paths/configs in the repo. I have downloaded the repo and config & run it from scratch to make sure it is indeed working right now.
